### ISSUE TITLE
0.4.0 broke conditional card inside

### ISSUE THREAD

**Issue by DrSpaldo** [ofekashery/vertical-stack-in-card#101]
Hi, I recently updated to 0.4.0 which fixed an ongoing issue. However, it appears it has created a new one instead. I had this conditional code within my vertical stack.

```
          - type: conditional
            conditions:
            - entity: fan.master_bedroom
              state: 'on'
            card:
              entities:
                - entity: input_number.dyson_fan_speed
                  name: Dyson Fan Speed
              type: entities
```
Now in 0.4.0 it displays no matter what, rather than being conditional.
