### ISSUE TITLE
Séparation horizontale & taille title

### ISSUE THREAD

**Issue by kweebix** [ofekashery/vertical-stack-in-card#102]
Bonjour alors que j'ai déclaré
Horizontal: false
Mes deux card se touche quand même une solution ?
Pouvons nous changer la taille du titre
![Screenshot_20210106-005158.jpg](https://user-images.githubusercontent.com/12646272/103712181-6bbca000-4fb9-11eb-9d0b-07da63f12ddf.jpg)![Screenshot_20210106-005150__01.jpg](https://user-images.githubusercontent.com/12646272/103712213-80009d00-4fb9-11eb-9101-9f30570db32f.jpg)

**Comment by ofekashery** [comment]
Hi @kweebix,
The card appears horizontal because you put it inside a ``horizontal-stack`` card.

You can change the card titles style with themes:
```yaml
frontend:
  themes:
    my_theme:
      ha-card-header-font-size: 14px
```
