### ISSUE TITLE
Invisible card

### ISSUE THREAD

**Issue by TTLucian** [ofekashery/vertical-stack-in-card#107]
I get an invisible card when using this:
```
type: vertical-stack
cards:
  - type: 'custom:vertical-stack-in-card'
    cards:
      - type: 'custom:simple-thermostat'
```

Works ok with this:
```
type: vertical-stack
cards:
  - type: vertical-stack
    cards:
      - type: 'custom:simple-thermostat'
```
and with this:
```
type: 'custom:vertical-stack-in-card'
cards:
  - type: 'custom:vertical-stack-in-card'
    cards:
      - type: 'custom:simple-thermostat'
