### ISSUE TITLE
BUG: vertical-Stack-in-card does not work properly with popular styling plugin "card-mod" (by thomasloven)

### ISSUE THREAD

**Issue by sstefanowski** [ofekashery/vertical-stack-in-card#108]
Hello,
I just noticed that vertical-Stack-in-card does not work properly with popular styling "card-mod".

**Symptoms:**
When you configure more than one vertical-stack-in-card on the same page the card-mod on one page changes it for all instances.
I wanted to have 4 instances with different background e.g. first with
```
title: Kitchen
type: 'custom:vertical-stack-in-card'
cards:
(...)
card_mod:
  style: |
    ha-card {
      background: url("/local/Kitchen.jpg") center no-repeat;
    }
```
second with
```
title: Livingroom
type: 'custom:vertical-stack-in-card'
cards:
(...)
card_mod:
  style: |
    ha-card {
      background: url("/local/Livingroom.jpg") center no-repeat;
    }
```
In Card the background is rendered correctly but after saving all cards change it's background JPG the one configured with last vertical-stack-in-card on the page. It looks like ha-card style is shared and will be always the same.

The other cards like "banner-card" or "theromostat-card" can have different background on the same page... so I think this is the BUG of  vertical-stack-in-card. 

Can you fix it to make it fully compatibe with "card-mod' by thomasloven?

**Versions:**
vertical-stack-in-card: 0.4.0
card-mod: 3.0.5
HA: 2021.1.5

**Comment by Zendio** [comment]
![image](https://user-images.githubusercontent.com/5435734/110622999-7f90a800-819c-11eb-8ad1-5cba3df6964d.png)
Not sure if this needs it's own thread. This card contains auto-entities entries. There were no gaps or rounded corners before updating thomasloven's frontend plugins.

**Comment by artem30801** [comment]
Are there any workaround you were able to find?

**Comment by ofekashery** [comment]
Hi @artem30801, please try this config:
```yaml
title: Kitchen
type: 'custom:vertical-stack-in-card'
styles:
  '--ha-card-background': 'url("/local/Kitchen.jpg") center no-repeat;'
cards:
(...)
```

**Comment by artem30801** [comment]
> Hi there, please try this config:
> 
> ```yaml
> title: Kitchen
> type: 'custom:vertical-stack-in-card'
> styles:
>   '--ha-card-background': 'url("/local/Kitchen.jpg") center no-repeat;'
> cards:
> (...)
> ```

Thank you for your reply! Tried this code (colors instead of images):
```yaml
  - title: Test
    cards:
      - title: Kitchen
        type: "custom:vertical-stack-in-card"
        card_mod:
          style: |
            ha-card {
              --ha-card-background: rgba(0, 255, 0, 1);
            }
        cards:
          - type: markdown
            content: >
              ## Lovelace
          - type: markdown
            content: >
              ## Lovelace2
      - title: Livingroom
        type: "custom:vertical-stack-in-card"
        card_mod:
          style: |
            ha-card {
              --ha-card-background: rgba(255, 0, 0, 1);
            }
        cards:
          - type: markdown
            content: >
              ## Lovelace3
          - type: markdown
            content: >
              ## Lovelace4
```
Result: (only last style applied, despite the fact that the first card should be green)
![image](https://user-images.githubusercontent.com/38689676/123444934-182e2500-d5e0-11eb-9296-9d1642c2ddfe.png)

I then tried your suggestion, @ofekashery , with code
```yaml
  - title: Test
    cards:
      - title: Kitchen
        type: "custom:vertical-stack-in-card"
        styles:
          "--ha-card-background": rgba(0, 255, 0, 1)
        cards:
          - type: markdown
            content: >
              ## Lovelace
          - type: markdown
            content: >
              ## Lovelace2
      - title: Livingroom
        type: "custom:vertical-stack-in-card"
        styles:
          "--ha-card-background": rgba(255, 0, 0, 1)
        cards:
          - type: markdown
            content: >
              ## Lovelace3
          - type: markdown
            content: >
              ## Lovelace4
```
Result: (it works as expected, but it only changes styles of child cards, not original vertical-stack-in-card)
![image](https://user-images.githubusercontent.com/38689676/123445827-f3867d00-d5e0-11eb-8688-507ace154ec4.png)
