### ISSUE TITLE
Card doesn't support attributes

### ISSUE THREAD

**Issue by phoniclynx** [ofekashery/vertical-stack-in-card#112]
```
type: vertical-stack
title: Calendar
cards:
  - type: entities
    entities:
    - entity: sensor.google_alarm_event
      icon: hass:alarm
      attribute: time
      name: Start
```
results in only the main status being displayed and not the attribute of the sensor (time)
