### ISSUE TITLE
Allow control space appearing between cards

### ISSUE THREAD

**Issue by ThomDietrich** [ofekashery/vertical-stack-in-card#130]
Hey there,
Assuming that vertical-stack-in-card should behave and feel identical to the core cards, there is one very obvious difference:

![image](https://user-images.githubusercontent.com/2870104/192753088-546def3e-487b-4fb0-aa9a-77bccad9c9d9.png)

The distance between the title and the first card should certainly be reduced. Equally I would argue to reduce the distance between cards, however I understand that this might squish certain card types together unpleasantly!?

I was able to resolve this by adding the following CSS rule (as applied in the core source). I am not a CSS expert, so please evaluate whether it's the best solution. Thanks!!

```css
vertical-stack-in-card div#states.card-content {
  margin-top: -8px;
  padding-top: 0px;
}
```
