### ISSUE TITLE
Vertical stack with mushroom select card

### ISSUE THREAD

**Issue by Smurf634** [ofekashery/vertical-stack-in-card#148]
I have a vertical stack with 2 mushroom select card in it.
When i open the dropdown menu i can't scroll true it.
It alsof doesn't fully open the dropdown menu. It only opens as big as the card is.

With this i don't have full acces of all the items in de dropdown menu.
![Screenshot_20230219_182709_Home Assistant](https://user-images.githubusercontent.com/82337508/219964398-7c23a6e5-8dd5-437b-9e3a-28690a5f15be.jpg)
![Screenshot_20230219_182718_Home Assistant](https://user-images.githubusercontent.com/82337508/219964399-9f2c8dd5-5abf-46e2-8ae1-410662c71b35.jpg)

**Comment by ofekashery** [comment]
Hi @Smurf634, please use the `styles` option:
```yaml
type: 'custom:vertical-stack-in-card'
styles: |
  ha-card {
  overflow: visible !important;
  }
```
