### ISSUE TITLE
Visual editor does not work with the label horizontal: true

### ISSUE THREAD

**Issue by BBE-FR** [ofekashery/vertical-stack-in-card#162]
Visual editor is a very nice addition to the latest version !!

It is working well, even if you use an horizontal stack inside a custom vertical stack to create a "fake" custom horizontal stack with visual editor:
![image](https://github.com/user-attachments/assets/8f1aad37-c851-4431-9329-d444d655fe6b)
like this
```
type: custom:vertical-stack-in-card
cards:
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-template-card
      etc...
```
You can see that in this case we have the same issue as https://github.com/ofekashery/vertical-stack-in-card/issues/150

But if you try to use the label `horizontal: true` to get rid of the horizontal stack, it works very well in YAML, without the borders appearing, but the visual editor is broken:

```
type: custom:vertical-stack-in-card
horizontal: true
cards:
  - type: custom:mushroom-template-card
  etc...
```
The visual editor does not work anymore:
![image](https://github.com/user-attachments/assets/1dd9d30c-2fc6-41e5-a7fd-ae4fe7b14e55)
With the following warning (translated from french) : 
```
Visual editor is not available for this configuration:
- "horizontal" key not expected or not available for visual editor 
You can edit your configuration through YAML
```

I know the card is named **vertical**-stack-in-card but it works so well that I think the horizontal option deserve to be implemented in the editor...

**Comment by ofekashery** [comment]
It's indeed a bug caused by using the visual editor implementation of `hui-vertical-stack-card`, which does not contain the `horizontal` option. I'll look into it - thanks for the report :)

**Comment by ofekashery** [comment]
The new release (`1.0.1`) is now support a visual editor also for horizontal cards 🪄

**Comment by ngocjohn** [comment]
Hi @ofekashery but the problem is that preview will always be vertical stack, every change in the editor will delete the label horizontal and the config will be saved without it. 🤷‍♂️

**Comment by pafnow** [comment]
> Hi @ofekashery but the problem is that preview will always be vertical stack, every change in the editor will delete the label horizontal and the config will be saved without it. 🤷‍♂️

+1

edit: i dont see any option for horizontal card in visual editor in 1.0.1

**Comment by ofekashery** [comment]
Thanks for the report @ngocjohn @pafnow  - I'm aware of this issue.

I'm working on a new solution which is introducing a new fresh editor for the card. Hope to update soon!

**Comment by ciotorcristian** [comment]
Any updates on this issue?

**Comment by lpt2007** [comment]
Any updates on this issue?

**Comment by Mastiffen** [comment]
It's not only eating "horizontal: true", it eats the full formatting, this all goes away:

```
          - type: custom:vertical-stack-in-card
            horizontal: true
            styles:
              margin-left: 2px
              margin-right: 2px
              margin-bottom: 4px
              border-style: solid
              border-color: black
              border-width: 2px
              border-radius: 10px
              height: 110px

```

I hope this card isn't abandoned, I really like it!
