### ISSUE TITLE
Issues with nesting a horizontal stack

### ISSUE THREAD

**Issue by Hypfer** [ofekashery/vertical-stack-in-card#38]
![image](https://user-images.githubusercontent.com/974410/50388600-b42efb00-071b-11e9-85ee-2c5b7a27b722.png)

```
type: 'custom:vertical-stack-in-card'
title: Draußen
cards:
  - type: 'custom:mini-graph-card'
    entity: sensor.virt_temperatur_aussen
    line_color: '#eb4d54'
    name: Temperatur
  - type: horizontal-stack
    cards:
      - entity: sensor.virt_luftfeuchtigkeit_aussen
        icon: 'mdi:water-percent'
        line_color: '#3a8df7'
        name: Rel. Hum.
        type: 'custom:mini-graph-card'
      - entity: sensor.virt_absolute_luftfeuchtigkeit_aussen
        icon: 'mdi:water'
        line_color: '#3a8df7'
        name: Abs. Hum.
        type: 'custom:mini-graph-card'
```

It seems like its only removing the border of the first child of the horizontal-stack card

**Comment by Mikomie** [comment]
I have a similar issue

when hassio first loads up lovelace it shows margin's on my inner cards (seems like there is no "margin:0px" on the <card-modder> inline yet, this happens after i open and close the menu, or go to another tab and then go back. when i press f5 the margin comes back. resizing the viewport also fixes the issue. I'm guessing that the script needs to load when the dom is fully loaded or something?

first load or after refreshing the page
![vertical-stack-page-refresh](https://user-images.githubusercontent.com/49552571/56901659-f33dd600-6a98-11e9-9856-d3cf0b3694c2.jpg)

looks after resizing the window, opening the menu, selecting another tab(view) and then going back
![vertical-stack-after-switching-tabs](https://user-images.githubusercontent.com/49552571/56901658-f33dd600-6a98-11e9-89f1-4081bbf17d19.jpg)

my code:
```
card:
  cards:
    - cards:
        - card:
            align_icon: right
            entities:
              - sensor.t6_temperature
            font_size_header: 20
            group: false
            name: Temperatuur
            show:
              extrema: false
              graph: false
              labels: false
              state: false
            type: 'custom:mini-graph-card'
            unit: °C
          style:
            border-radius: 15px 15px 0px 0px
          type: 'custom:card-modder'
      type: horizontal-stack
    - cards:
        - card:
            align_icon: left
            align_state: center
            entities:
              - sensor.t6_temperature
            font_size: 167
            group: false
            line-width: 1
            name: Temperatuur
            show:
              extrema: false
              graph: false
              icon: false
              labels: false
              name: false
              state: true
            type: 'custom:mini-graph-card'
            unit: °C
          style:
            border-radius: 0px 0px 0px 0px
            color: var(--paper-item-icon-color)
            height: 168px
            justify-content: center
            margin: 0px !important
          type: 'custom:card-modder'
        - card:
            entity: climate.lyric_t6
            hide:
              state: true
              temperature: true
            name: false
            step-size: 0.5
            type: 'custom:simple-thermostat'
          style:
            border-radius: 0px 0px 0px 0px
            height: 168px
            margin: 0px !important
          type: 'custom:card-modder'
      type: horizontal-stack
    - cards:
        - card:
            align_icon: left
            color_thresholds:
              - color: '#5d86ee'
                value: 0
              - color: '#86ee5d'
                value: 18
              - color: '#eec55d'
                value: 23
              - color: '#ee7d5d'
                value: 26
            entities:
              - sensor.t6_temperature
            font_size: 167
            font_size_header: 20
            group: false
            line-width: 1
            name: Temperatuur
            show:
              extrema: false
              graph: line
              icon: false
              labels: true
              name: false
              points: true
              state: false
            type: 'custom:mini-graph-card'
            unit: °C
          style:
            border-radius: 0px 0px 15px 15px
          type: 'custom:card-modder'
      style: null
      type: horizontal-stack
  type: 'custom:vertical-stack-in-card'
style:
  margin: 0px !important
type: 'custom:card-modder'

```
