### ISSUE TITLE
Does not support special row elements

### ISSUE THREAD

**Issue by tomlut** [ofekashery/vertical-stack-in-card#56]
When adding an entities card all is well except if special row elements are included.

https://www.home-assistant.io/lovelace/entities/#special-row-elements

e.g. `type: divider` throws an error in this:

```
cards:
  - type: entities
    entities:
      - entity: switch.lounge_dehumidifier
      - type: divider
      - entity: automation.lounge_dehumidifier_direct_automation
      - entity: input_number.rumpus_dehumidifier_condensation_set
      - entity: input_number.lounge_dehumidifier_outside_temp_set
      - type: divider
      - entity: automation.lounge_dehumidifier_forecast_automation
      - entity: input_datetime.lounge_dehmidifier_run_time
      - entity: input_number.lounge_dehumidifier_rh_set
      - entity: input_number.lounge_dehumidifier_forecast_temp_set
      - type: divider
      - entity: input_boolean.lounge_dehumidifier_only_run_if_away
      - entity: input_boolean.lounge_dehumidifier_mute_for_movie
      - entity: input_number.lounge_dehumidifier_run_time
      - show_header_toggle: false
  - color_thresholds:
      - color: '#0da035'
        value: -1
      - color: '#e0b400'
        value: 1800
      - color: '#e45e65'
        value: 2100
    entities:
      - sensor.lounge_dehumidifier_power
    group: false
    hour24: true
    line_width: 2
    points_per_hour: 12
    show:
      icon: false
      labels: true
      name: false
      state: true
    type: 'custom:mini-graph-card'
title: Lounge Dehumidifier Control
type: 'custom:vertical-stack-in-card'
```
The entities card when not used in a vertical-stack-in-card displays as expected.
