### ISSUE TITLE
Space appearing between different entities

### ISSUE THREAD

**Issue by drthanwho** [ofekashery/vertical-stack-in-card#73]
Hi guys, 

I am using vertical-stack-in-card in conjunction with horizontal-card and button-card. At first it seemed to work just perfect, but now it will occasionally display the entities with gaps in between like so: 

![image](https://user-images.githubusercontent.com/22405505/71770303-58e93880-2f2b-11ea-9d11-104bf6552072.png)
![image](https://user-images.githubusercontent.com/22405505/71770353-e0cf4280-2f2b-11ea-920f-2e40908e7815.png)

Here is an example of the setup with one entity:

```yaml
type: 'custom:vertical-stack-in-card'
cards:
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        color_type: card
        entity: binary_sensor.pir_sensor
        show_last_changed: true
        size: 50%
        styles:
          name:
            - font-size: 12px
            - font-weight: bold
          label:
            - font-size: 12px
        state:
          - value: 'on'
            color: yellow
            icon: 'mdi:motion-sensor'
            styles:
              card:
                - animation: blink 2s linear infinite
          - operator: default
            color: null
            icon: 'mdi:motion-sensor'
```

**Comment by jonohunt** [comment]
I’ve noticed extra spacing between the title at the top and the entities below compared to ‘regular’ cards.

![vertical-stack-in-card](https://user-images.githubusercontent.com/2163340/78594528-61aa1d00-7840-11ea-9437-5dd05e4b40f8.jpeg)

Would be great if this was fixed, or if we could be able to tweak the padding ourselves.

**Comment by ttaidapos** [comment]
Yup I'm seeing this as well and it's not with all the cards either.  Below is what i'm seeing, i've noticed this with entity-filter cards and a few others.

![image](https://user-images.githubusercontent.com/27898709/80492362-84a08c00-8929-11ea-886a-2bc7176bd973.png)

```
type: 'custom:vertical-stack-in-card'
cards:
  - entities:
      - entity: input_boolean.modem_reboot
        icon: 'mdi:access-point'
        name: Modem Reboot
      - entity: input_boolean.router_reboot
        icon: 'mdi:router-wireless'
        name: Router Reboot
    show_header_toggle: false
    title: System Status
    type: entities
  - type: thermostat
    entity: climate.dining_room
  - type: entity-filter
    entities:
      - sensor.front_door_keypad_battery
      - sensor.water_battery_level
    state_filter:
      - operator: '>'
        value: 50
  - type: entities
    entities:
      - entity: sensor.dark_sky_precip_probability_0d
      - entity: sensor.dark_sky_apparent_temperature
```
