### ISSUE TITLE
vertical-stack-in-card 0.3.x overrides style from theme

### ISSUE THREAD

**Issue by bieniu** [ofekashery/vertical-stack-in-card#81]
I use theme with `ha-card-border-radius`:
```
blue-mix:
  primary-color: '#5294e2'
  dark-primary-color: '#0067b0'
  light-primary-color: '#89c4ff'
  accent-color: '#ffb750'
  state-icon-color: 'var(--dark-primary-color)'
  state-icon-active-color: '#ffb750'
  ha-card-border-radius: '10px'
```
After update `vertical-stack-in-card` to version 0.3.0 border radius disappeared.
![image](https://user-images.githubusercontent.com/478555/77322154-90d66f80-6d13-11ea-87c9-e8982c3936db.png)
