### ISSUE TITLE
Seems to not work on .107.7 with new media-control card, error "Custom element doesn't exist: hui-media-control-card."

### ISSUE THREAD

**Issue by scstraus** [ofekashery/vertical-stack-in-card#85]
I've been using vertical-stack-in for quite a while and it's always worked well.. But I just can't get it to work properly with the new media-control card.

This is my config which doesn't work:
```
  - type: custom:vertical-stack-in-card
    cards:
    - type: media-control
      entity: media_player.itunes 
    - type: entities
      entities:
      - type: custom:slider-entity-row
        entity: media_player.itunes
        full_row: true
```
This, however works okay (though obviously not combined as a stack-in):
```
  - type: media-control
    entity: media_player.itunes 
  - type: custom:vertical-stack-in-card
    cards:
    - type: entities
      entities:
      - type: custom:slider-entity-row
        entity: media_player.itunes
        full_row: true
```
Here's what it looks like:
![image](https://user-images.githubusercontent.com/7644023/78196379-838f5280-7482-11ea-8ffd-bed1e51b2c86.png)

**Comment by ofekashery** [comment]
Hi @scstraus! 
Can you make sure you're using the [latest version](https://github.com/ofekashery/vertical-stack-in-card/releases/latest)?
Also, please add the new version number to the end of the cards reference url in your ``ui-lovelace.yaml``/``configuration.yaml`` like below:
```yaml
resources:
  - url: /local/vertical-stack-in-card.js?v=0.3.2
    type: js
```
