### ISSUE TITLE
Custom element doesn't exist: vertical-stack-in-card.

### ISSUE THREAD

**Issue by thundergreen** [ofekashery/vertical-stack-in-card#86]
```
type: 'custom:vertical-stack-in-card'
title: Light Test Card
cards:
  - type: glance
    entities:
      - light.chill_out_corner
      - light.hyperion
      - light.led_glashouse
      - light.led_strip_living_room
      - light.spots_living_room
      - light.wled_glashouse
      - light.wood_lamp_chill_out_corner
  - type: entities
    entities:
      - scene.day_light
      - scene.morning_light
      - scene.movie_time
      - scene.night_light
```

I am using latest release, reloaded ressources but still not showing
