### ISSUE TITLE
Card do not work when inside an !include

### ISSUE THREAD

**Issue by yuvalabou** [ofekashery/vertical-stack-in-card#87]
Tried to compact my ``lovelace.yaml`` file with ``!include`` and when inside the external YAML file it says ``no card type configured`` - However - when using normal vertical stack it is working as expected.

THIS IS WORKING -
```yaml
type: vertical-stack
cards:
  - type: picture-elements
    image: /local/assets/vacuum_banner.jpg
    elements:
      - type: state-label
        entity: vacuum.xiaomi_vacuum_cleaner
```

AND THIS IS NOT -
```yaml
type: 'custom:vertical-stack-in-card'
cards:
  - type: picture-elements
    image: /local/assets/vacuum_banner.jpg
    elements:
      - type: state-label
        entity: vacuum.xiaomi_vacuum_cleaner
```

(the dash is missing in front of "type" because it is in front of the ``!include`` command in the main lovelace.

thanks.
