### ISSUE TITLE
Enhancement: Enable header icon and toggle (like entities card)

### ISSUE THREAD

**Issue by JesseWebDotCom** [ofekashery/vertical-stack-in-card#94]
I'd love to have a header icon and toggle like the entities card (toggle to turn off and on the entities within the card)

**Comment by flyingdutchman31** [comment]
As an alternative I use the [banner card ](https://github.com/nervetattoo/banner-card) in combination with the custom:vertical-stack-card.

Below is my code for eacht vertical-stack-in-card in combination with the banner card
type: custom:vertical-stack-in-card
horizontal: false
cards:
  - type: custom:banner-card
    heading:
      - hass:tree
      - Garden
    background: SlateGray

**Comment by ofekashery** [comment]
This feature isn't directly related to VSIC and I don't see it coming into the card.
I suggest using a `entities` card inside a `vertical-stack-in-card`, thus getting the same result you wanted.

```
type: custom:vertical-stack-in-card
cards:
  - type: entities
    title: My card
    show_header_toggle: true
    entities:
        ...
```
