### ISSUE TITLE
The vertical-stack-in-card section is not visible in the dashboard

### ISSUE THREAD

**Issue by xMariusz** [ofekashery/vertical-stack-in-card#97]
The vertical-stack-in-card section is not visible in the dashboard. I often have to refresh the page to display correctly

My code:
```
cards:
  - entities:
      - binary_sensor.updater
      - sensor.up_time
      - sensor.last_boot
      - sensor.hl_1210w_drum_remaining_life
    title: System
    type: glance
type: 'custom:vertical-stack-in-card'

```
Version 0.3.3. 
Home Assistant 0.116.2

Any solution?

![Adnotacja 2020-10-15 143237](https://user-images.githubusercontent.com/21967796/96123613-5e7ca180-0ef3-11eb-9d4d-4850fef3da4a.png)
